networks:
  cassandra_network:
    ipam:
      config:
      - subnet: 192.168.100.0/24
services:
  cassandra11:
    image: docker.io/library/cassandra:latest
    hostname: cassandra11
    container_name: cassandra11
    mem_limit: 1g
    cpus: 0.5
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.111
    volumes:
    - ./docker/cassandra11:/bitnami
    environment:
    - CASSANDRA_CLUSTER_NAME=formation
    - CASSANDRA_SEEDS=cassandra11,cassandra21
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DATACENTER=Nord
    - CASSANDRA_RACK=Winterfell1
    - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.100.111
    - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
    - MAX_HEAP_SIZE=256m
    - HEAP_NEWSIZE=50m
    ports:
    - 7100:7000
    - 9142:9042
    healthcheck:
      test:
      - CMD-SHELL
      - '[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running
        ]'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  cassandra12:
    depends_on:
      cassandra11:
        condition: service_healthy
    image: docker.io/library/cassandra:latest
    hostname: cassandra12
    container_name: cassandra12
    mem_limit: 1g
    cpus: 0.5
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.112
    volumes:
    - ./docker/cassandra12:/bitnami
    environment:
    - CASSANDRA_CLUSTER_NAME=formation
    - CASSANDRA_SEEDS=cassandra11,cassandra21
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DATACENTER=Nord
    - CASSANDRA_RACK=Winterfell2
    - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.100.112
    - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
    - MAX_HEAP_SIZE=256m
    - HEAP_NEWSIZE=50m
    ports:
    - 7200:7000
    - 9242:9042
    healthcheck:
      test:
      - CMD-SHELL
      - '[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running
        ]'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  cassandra13:
    depends_on:
      cassandra12:
        condition: service_healthy
    image: docker.io/library/cassandra:latest
    hostname: cassandra13
    container_name: cassandra13
    mem_limit: 1g
    cpus: 0.5
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.113
    volumes:
    - ./docker/cassandra13:/bitnami
    environment:
    - CASSANDRA_CLUSTER_NAME=formation
    - CASSANDRA_SEEDS=cassandra11,cassandra21
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DATACENTER=Nord
    - CASSANDRA_RACK=Winterfell3
    - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.100.113
    - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
    - MAX_HEAP_SIZE=256m
    - HEAP_NEWSIZE=50m
    ports:
    - 7300:7000
    - 9342:9042
    healthcheck:
      test:
      - CMD-SHELL
      - '[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running
        ]'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  cassandra21:
    depends_on:
      cassandra13:
        condition: service_healthy
    image: docker.io/library/cassandra:latest
    hostname: cassandra21
    container_name: cassandra21
    mem_limit: 1g
    cpus: 0.5
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.121
    volumes:
    - ./docker/cassandra21:/bitnami
    environment:
    - CASSANDRA_CLUSTER_NAME=formation
    - CASSANDRA_SEEDS=cassandra11,cassandra21
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DATACENTER=Terres-de-la-Couronne
    - CASSANDRA_RACK=Port-Real1
    - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.100.121
    - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
    - MAX_HEAP_SIZE=256m
    - HEAP_NEWSIZE=50m
    ports:
    - 7400:7000
    - 9442:9042
    healthcheck:
      test:
      - CMD-SHELL
      - '[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running
        ]'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  cassandra22:
    depends_on:
      cassandra21:
        condition: service_healthy
    image: docker.io/library/cassandra:latest
    hostname: cassandra22
    container_name: cassandra22
    mem_limit: 1g
    cpus: 0.5
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.122
    volumes:
    - ./docker/cassandra22:/bitnami
    environment:
    - CASSANDRA_CLUSTER_NAME=formation
    - CASSANDRA_SEEDS=cassandra11,cassandra21
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DATACENTER=Terres-de-la-Couronne
    - CASSANDRA_RACK=Port-Real2
    - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.100.122
    - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
    - MAX_HEAP_SIZE=256m
    - HEAP_NEWSIZE=50m
    ports:
    - 7500:7000
    - 9542:9042
    healthcheck:
      test:
      - CMD-SHELL
      - '[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running
        ]'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  cassandra23:
    depends_on:
      cassandra22:
        condition: service_healthy
    image: docker.io/library/cassandra:latest
    hostname: cassandra23
    container_name: cassandra23
    mem_limit: 1g
    cpus: 0.5
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.123
    volumes:
    - ./docker/cassandra23:/bitnami
    environment:
    - CASSANDRA_CLUSTER_NAME=formation
    - CASSANDRA_SEEDS=cassandra11,cassandra21
    - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    - CASSANDRA_DATACENTER=Terres-de-la-Couronne
    - CASSANDRA_RACK=Port-Real3
    - CASSANDRA_BROADCAST_RPC_ADDRESS=192.168.100.123
    - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
    - MAX_HEAP_SIZE=256m
    - HEAP_NEWSIZE=50m
    ports:
    - 7600:7000
    - 9642:9042
    healthcheck:
      test:
      - CMD-SHELL
      - '[ $$(nodetool -h 127.0.0.1 -pw cassandra -u cassandra statusgossip) = running
        ]'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    container_name: prometheus
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.150
    ports:
    - 9090:9090
    volumes:
    - ./docker/prometheus/config:/etc/prometheus
    - ./docker/prometheus/data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --storage.tsdb.retention.time=200h
    - --web.enable-lifecycle
    user: 1000:1000
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.151
    ports:
    - 3000:3000
    volumes:
    - ./docker/grafana/data:/var/lib/grafana
    - ./docker/grafana/config:/etc/grafana/provisioning
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin123
    - GF_USERS_ALLOW_SIGN_UP=false
    user: 1000:1000
  cassandra-jmx-exporter:
    image: bitnami/jmx-exporter:latest
    hostname: cassandra-jmx-exporter
    container_name: cassandra-jmx-exporter
    restart: always
    networks:
      cassandra_network:
        ipv4_address: 192.168.100.152
    ports:
    - 8080:8080
    volumes:
    - ./docker/jmx-exporter/config:/opt/jmx_exporter/config
    command:
    - '8080'
    - /opt/jmx_exporter/config/cassandra.yml
